version: '3.8'

services:
  initphp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
      - 443:443
    volumes:
      - ./system/Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./system/Docker/nginx/sites-available/default.conf:/etc/nginx/sites-available/default
      - ./system/Docker/php-fpm/php-fpm.conf:/etc/php/8.1/fpm/php-fpm.conf
      - ./:/var/www/html/
    container_name: 'initphp'
    working_dir: /var/www/html
    restart: always
    networks:
      - initphpnet

networks:
  initphpnet: